import '../../l10n/generated/app_localizations.dart';

extension AppLocalizationsScaleKeys on AppLocalizations {
  // Map estático: inicializado una sola vez, lookup O(1).
  // El assert en resolveKey() captura claves no registradas en debug mode.
  static final Map<String, String Function(AppLocalizations)> _keys = {
    // ── Severity ──────────────────────────────────────────────────────
    'severityNone': (l) => l.severityNone,
    'severityMild': (l) => l.severityMild,
    'severityModerate': (l) => l.severityModerate,
    'severitySevere': (l) => l.severitySevere,

    // ── GCS labels ────────────────────────────────────────────────────
    'gcsEyeLabel': (l) => l.gcsEyeLabel,
    'gcsVerbalLabel': (l) => l.gcsVerbalLabel,
    'gcsMotorLabel': (l) => l.gcsMotorLabel,
    // GCS options
    'gcsEyeOpt1': (l) => l.gcsEyeOpt1,
    'gcsEyeOpt2': (l) => l.gcsEyeOpt2,
    'gcsEyeOpt3': (l) => l.gcsEyeOpt3,
    'gcsEyeOpt4': (l) => l.gcsEyeOpt4,
    'gcsVerbalOpt1': (l) => l.gcsVerbalOpt1,
    'gcsVerbalOpt2': (l) => l.gcsVerbalOpt2,
    'gcsVerbalOpt3': (l) => l.gcsVerbalOpt3,
    'gcsVerbalOpt4': (l) => l.gcsVerbalOpt4,
    'gcsVerbalOpt5': (l) => l.gcsVerbalOpt5,
    'gcsMotorOpt1': (l) => l.gcsMotorOpt1,
    'gcsMotorOpt2': (l) => l.gcsMotorOpt2,
    'gcsMotorOpt3': (l) => l.gcsMotorOpt3,
    'gcsMotorOpt4': (l) => l.gcsMotorOpt4,
    'gcsMotorOpt5': (l) => l.gcsMotorOpt5,
    'gcsMotorOpt6': (l) => l.gcsMotorOpt6,

    // ── ABCD2 interpretations ─────────────────────────────────────────
    'abcd2RiskLow': (l) => l.abcd2RiskLow,
    'abcd2RiskModerate': (l) => l.abcd2RiskModerate,
    'abcd2RiskHigh': (l) => l.abcd2RiskHigh,

    // ── Barthel interpretations ───────────────────────────────────────
    'barthelInterpIndependent': (l) => l.barthelInterpIndependent,
    'barthelInterpMild': (l) => l.barthelInterpMild,
    'barthelInterpModerate': (l) => l.barthelInterpModerate,
    'barthelInterpSevere': (l) => l.barthelInterpSevere,
    'barthelInterpTotal': (l) => l.barthelInterpTotal,

    // ── Rankin interpretations ────────────────────────────────────────
    'rankinInterp0': (l) => l.rankinInterp0,
    'rankinInterp1': (l) => l.rankinInterp1,
    'rankinInterp2': (l) => l.rankinInterp2,
    'rankinInterp3': (l) => l.rankinInterp3,
    'rankinInterp4': (l) => l.rankinInterp4,
    'rankinInterp5': (l) => l.rankinInterp5,
    'rankinInterp6': (l) => l.rankinInterp6,

    // ── NIHSS interpretations ─────────────────────────────────────────
    'nihssInterp0': (l) => l.nihssInterp0,
    'nihssInterpMinor': (l) => l.nihssInterpMinor,
    'nihssInterpModerate': (l) => l.nihssInterpModerate,
    'nihssInterpModerateSevere': (l) => l.nihssInterpModerateSevere,
    'nihssInterpSevere': (l) => l.nihssInterpSevere,

    // ── ABCD2 labels ──────────────────────────────────────────────────
    'abcd2AgeLabel': (l) => l.abcd2AgeLabel,
    'abcd2BpLabel': (l) => l.abcd2BpLabel,
    'abcd2ClinicalLabel': (l) => l.abcd2ClinicalLabel,
    'abcd2DurationLabel': (l) => l.abcd2DurationLabel,
    'abcd2DiabetesLabel': (l) => l.abcd2DiabetesLabel,
    // ABCD2 options
    'abcd2AgeOpt0': (l) => l.abcd2AgeOpt0,
    'abcd2AgeOpt1': (l) => l.abcd2AgeOpt1,
    'abcd2BpOpt0': (l) => l.abcd2BpOpt0,
    'abcd2BpOpt1': (l) => l.abcd2BpOpt1,
    'abcd2ClinicalOpt0': (l) => l.abcd2ClinicalOpt0,
    'abcd2ClinicalOpt1': (l) => l.abcd2ClinicalOpt1,
    'abcd2ClinicalOpt2': (l) => l.abcd2ClinicalOpt2,
    'abcd2DurationOpt0': (l) => l.abcd2DurationOpt0,
    'abcd2DurationOpt1': (l) => l.abcd2DurationOpt1,
    'abcd2DurationOpt2': (l) => l.abcd2DurationOpt2,
    'abcd2DiabetesOpt0': (l) => l.abcd2DiabetesOpt0,
    'abcd2DiabetesOpt1': (l) => l.abcd2DiabetesOpt1,

    // ── Barthel labels ────────────────────────────────────────────────
    'barthelItemFeeding': (l) => l.barthelItemFeeding,
    'barthelItemBathing': (l) => l.barthelItemBathing,
    'barthelItemGrooming': (l) => l.barthelItemGrooming,
    'barthelItemDressing': (l) => l.barthelItemDressing,
    'barthelItemBowels': (l) => l.barthelItemBowels,
    'barthelItemBladder': (l) => l.barthelItemBladder,
    'barthelItemToiletUse': (l) => l.barthelItemToiletUse,
    'barthelItemTransfer': (l) => l.barthelItemTransfer,
    'barthelItemMobility': (l) => l.barthelItemMobility,
    'barthelItemStairs': (l) => l.barthelItemStairs,
    // Barthel options
    'barthelFeedingOpt0': (l) => l.barthelFeedingOpt0,
    'barthelFeedingOpt5': (l) => l.barthelFeedingOpt5,
    'barthelFeedingOpt10': (l) => l.barthelFeedingOpt10,
    'barthelBathingOpt0': (l) => l.barthelBathingOpt0,
    'barthelBathingOpt5': (l) => l.barthelBathingOpt5,
    'barthelGroomingOpt0': (l) => l.barthelGroomingOpt0,
    'barthelGroomingOpt5': (l) => l.barthelGroomingOpt5,
    'barthelDressingOpt0': (l) => l.barthelDressingOpt0,
    'barthelDressingOpt5': (l) => l.barthelDressingOpt5,
    'barthelDressingOpt10': (l) => l.barthelDressingOpt10,
    'barthelBowelsOpt0': (l) => l.barthelBowelsOpt0,
    'barthelBowelsOpt5': (l) => l.barthelBowelsOpt5,
    'barthelBowelsOpt10': (l) => l.barthelBowelsOpt10,
    'barthelBladderOpt0': (l) => l.barthelBladderOpt0,
    'barthelBladderOpt5': (l) => l.barthelBladderOpt5,
    'barthelBladderOpt10': (l) => l.barthelBladderOpt10,
    'barthelToiletUseOpt0': (l) => l.barthelToiletUseOpt0,
    'barthelToiletUseOpt5': (l) => l.barthelToiletUseOpt5,
    'barthelToiletUseOpt10': (l) => l.barthelToiletUseOpt10,
    'barthelTransferOpt0': (l) => l.barthelTransferOpt0,
    'barthelTransferOpt5': (l) => l.barthelTransferOpt5,
    'barthelTransferOpt10': (l) => l.barthelTransferOpt10,
    'barthelTransferOpt15': (l) => l.barthelTransferOpt15,
    'barthelMobilityOpt0': (l) => l.barthelMobilityOpt0,
    'barthelMobilityOpt5': (l) => l.barthelMobilityOpt5,
    'barthelMobilityOpt10': (l) => l.barthelMobilityOpt10,
    'barthelMobilityOpt15': (l) => l.barthelMobilityOpt15,
    'barthelStairsOpt0': (l) => l.barthelStairsOpt0,
    'barthelStairsOpt5': (l) => l.barthelStairsOpt5,
    'barthelStairsOpt10': (l) => l.barthelStairsOpt10,

    // ── Rankin label + options ────────────────────────────────────────
    'rankinScoreLabel': (l) => l.rankinScoreLabel,
    'rankinLevel0': (l) => l.rankinLevel0,
    'rankinLevel1': (l) => l.rankinLevel1,
    'rankinLevel2': (l) => l.rankinLevel2,
    'rankinLevel3': (l) => l.rankinLevel3,
    'rankinLevel4': (l) => l.rankinLevel4,
    'rankinLevel5': (l) => l.rankinLevel5,
    'rankinLevel6': (l) => l.rankinLevel6,

    // ── NIHSS labels ──────────────────────────────────────────────────
    'nihss1aLocLabel': (l) => l.nihss1aLocLabel,
    'nihss1bLocQuestionsLabel': (l) => l.nihss1bLocQuestionsLabel,
    'nihss1cLocCommandsLabel': (l) => l.nihss1cLocCommandsLabel,
    'nihss2GazeLabel': (l) => l.nihss2GazeLabel,
    'nihss3VisualLabel': (l) => l.nihss3VisualLabel,
    'nihss4FacialLabel': (l) => l.nihss4FacialLabel,
    'nihss5aMotorArmLLabel': (l) => l.nihss5aMotorArmLLabel,
    'nihss5bMotorArmRLabel': (l) => l.nihss5bMotorArmRLabel,
    'nihss6aMotorLegLLabel': (l) => l.nihss6aMotorLegLLabel,
    'nihss6bMotorLegRLabel': (l) => l.nihss6bMotorLegRLabel,
    'nihss7AtaxiaLabel': (l) => l.nihss7AtaxiaLabel,
    'nihss8SensoryLabel': (l) => l.nihss8SensoryLabel,
    'nihss9LanguageLabel': (l) => l.nihss9LanguageLabel,
    'nihss10DysarthriaLabel': (l) => l.nihss10DysarthriaLabel,
    'nihss11NeglectLabel': (l) => l.nihss11NeglectLabel,
    // NIHSS options
    'nihss1aLocOpt0': (l) => l.nihss1aLocOpt0,
    'nihss1aLocOpt1': (l) => l.nihss1aLocOpt1,
    'nihss1aLocOpt2': (l) => l.nihss1aLocOpt2,
    'nihss1aLocOpt3': (l) => l.nihss1aLocOpt3,
    'nihss1bLocQuestionsOpt0': (l) => l.nihss1bLocQuestionsOpt0,
    'nihss1bLocQuestionsOpt1': (l) => l.nihss1bLocQuestionsOpt1,
    'nihss1bLocQuestionsOpt2': (l) => l.nihss1bLocQuestionsOpt2,
    'nihss1cLocCommandsOpt0': (l) => l.nihss1cLocCommandsOpt0,
    'nihss1cLocCommandsOpt1': (l) => l.nihss1cLocCommandsOpt1,
    'nihss1cLocCommandsOpt2': (l) => l.nihss1cLocCommandsOpt2,
    'nihss2GazeOpt0': (l) => l.nihss2GazeOpt0,
    'nihss2GazeOpt1': (l) => l.nihss2GazeOpt1,
    'nihss2GazeOpt2': (l) => l.nihss2GazeOpt2,
    'nihss3VisualOpt0': (l) => l.nihss3VisualOpt0,
    'nihss3VisualOpt1': (l) => l.nihss3VisualOpt1,
    'nihss3VisualOpt2': (l) => l.nihss3VisualOpt2,
    'nihss3VisualOpt3': (l) => l.nihss3VisualOpt3,
    'nihss4FacialOpt0': (l) => l.nihss4FacialOpt0,
    'nihss4FacialOpt1': (l) => l.nihss4FacialOpt1,
    'nihss4FacialOpt2': (l) => l.nihss4FacialOpt2,
    'nihss4FacialOpt3': (l) => l.nihss4FacialOpt3,
    'nihssMotorArmOpt0': (l) => l.nihssMotorArmOpt0,
    'nihssMotorArmOpt1': (l) => l.nihssMotorArmOpt1,
    'nihssMotorArmOpt2': (l) => l.nihssMotorArmOpt2,
    'nihssMotorArmOpt3': (l) => l.nihssMotorArmOpt3,
    'nihssMotorArmOpt4': (l) => l.nihssMotorArmOpt4,
    'nihssMotorArmOpt9': (l) => l.nihssMotorArmOpt9,
    'nihssMotorLegOpt0': (l) => l.nihssMotorLegOpt0,
    'nihssMotorLegOpt1': (l) => l.nihssMotorLegOpt1,
    'nihssMotorLegOpt2': (l) => l.nihssMotorLegOpt2,
    'nihssMotorLegOpt3': (l) => l.nihssMotorLegOpt3,
    'nihssMotorLegOpt4': (l) => l.nihssMotorLegOpt4,
    'nihssMotorLegOpt9': (l) => l.nihssMotorLegOpt9,
    'nihss7AtaxiaOpt0': (l) => l.nihss7AtaxiaOpt0,
    'nihss7AtaxiaOpt1': (l) => l.nihss7AtaxiaOpt1,
    'nihss7AtaxiaOpt2': (l) => l.nihss7AtaxiaOpt2,
    'nihss7AtaxiaOpt9': (l) => l.nihss7AtaxiaOpt9,
    'nihss8SensoryOpt0': (l) => l.nihss8SensoryOpt0,
    'nihss8SensoryOpt1': (l) => l.nihss8SensoryOpt1,
    'nihss8SensoryOpt2': (l) => l.nihss8SensoryOpt2,
    'nihss9LanguageOpt0': (l) => l.nihss9LanguageOpt0,
    'nihss9LanguageOpt1': (l) => l.nihss9LanguageOpt1,
    'nihss9LanguageOpt2': (l) => l.nihss9LanguageOpt2,
    'nihss9LanguageOpt3': (l) => l.nihss9LanguageOpt3,
    'nihss10DysarthriaOpt0': (l) => l.nihss10DysarthriaOpt0,
    'nihss10DysarthriaOpt1': (l) => l.nihss10DysarthriaOpt1,
    'nihss10DysarthriaOpt2': (l) => l.nihss10DysarthriaOpt2,
    'nihss10DysarthriaOpt9': (l) => l.nihss10DysarthriaOpt9,
    'nihss11NeglectOpt0': (l) => l.nihss11NeglectOpt0,
    'nihss11NeglectOpt1': (l) => l.nihss11NeglectOpt1,
    'nihss11NeglectOpt2': (l) => l.nihss11NeglectOpt2,

    // ── Tutorial: descripciones clínicas + referencia (Fase 7.3) ──────
    'gcsEyeHelp': (l) => l.gcsEyeHelp,
    'gcsVerbalHelp': (l) => l.gcsVerbalHelp,
    'gcsMotorHelp': (l) => l.gcsMotorHelp,
    'nihss1aLocHelp': (l) => l.nihss1aLocHelp,
    'nihss1bLocQuestionsHelp': (l) => l.nihss1bLocQuestionsHelp,
    'nihss1cLocCommandsHelp': (l) => l.nihss1cLocCommandsHelp,
    'nihss2GazeHelp': (l) => l.nihss2GazeHelp,
    'nihss3VisualHelp': (l) => l.nihss3VisualHelp,
    'nihss4FacialHelp': (l) => l.nihss4FacialHelp,
    'nihss5aMotorArmHelp': (l) => l.nihss5aMotorArmHelp,
    'nihss6aMotorLegHelp': (l) => l.nihss6aMotorLegHelp,
    'nihss7AtaxiaHelp': (l) => l.nihss7AtaxiaHelp,
    'nihss8SensoryHelp': (l) => l.nihss8SensoryHelp,
    'nihss9LanguageHelp': (l) => l.nihss9LanguageHelp,
    'nihss10DysarthriaHelp': (l) => l.nihss10DysarthriaHelp,
    'nihss11NeglectHelp': (l) => l.nihss11NeglectHelp,
    'barthelFeedingHelp': (l) => l.barthelFeedingHelp,
    'barthelBathingHelp': (l) => l.barthelBathingHelp,
    'barthelGroomingHelp': (l) => l.barthelGroomingHelp,
    'barthelDressingHelp': (l) => l.barthelDressingHelp,
    'barthelBowelsHelp': (l) => l.barthelBowelsHelp,
    'barthelBladderHelp': (l) => l.barthelBladderHelp,
    'barthelToiletUseHelp': (l) => l.barthelToiletUseHelp,
    'barthelTransferHelp': (l) => l.barthelTransferHelp,
    'barthelMobilityHelp': (l) => l.barthelMobilityHelp,
    'barthelStairsHelp': (l) => l.barthelStairsHelp,
    'abcd2AgeHelp': (l) => l.abcd2AgeHelp,
    'abcd2BpHelp': (l) => l.abcd2BpHelp,
    'abcd2ClinicalHelp': (l) => l.abcd2ClinicalHelp,
    'abcd2DurationHelp': (l) => l.abcd2DurationHelp,
    'abcd2DiabetesHelp': (l) => l.abcd2DiabetesHelp,
  };

  // Aliases para valores legacy guardados antes de Fase 4.3 (2026-04-30).
  // Corregidos en BD por migración 0008; este mapa actúa como red de seguridad.
  static const Map<String, String> _legacyAliases = {
    // ABCD2 legacy (pre Fase 4.3)
    'Riesgo bajo (~1.0%)': 'abcd2RiskLow',
    'Riesgo moderado (~4.1%)': 'abcd2RiskModerate',
    'Riesgo alto (~8.1%)': 'abcd2RiskHigh',
    // NIHSS legacy (pre Fase 4.3)
    'Sin déficit': 'nihssInterp0',
    'Ictus menor (1-4)': 'nihssInterpMinor',
    'Ictus moderado (5-15)': 'nihssInterpModerate',
    'Ictus moderado-grave (16-20)': 'nihssInterpModerateSevere',
    'Ictus grave (21-42)': 'nihssInterpSevere',
  };

  String resolveKey(String key) {
    final canonical = _legacyAliases[key] ?? key;
    final fn = _keys[canonical];
    assert(
      fn != null,
      'resolveKey: clave "$key" no registrada en scale_key_resolver',
    );
    return fn?.call(this) ?? key;
  }
}
