import '../../l10n/generated/app_localizations.dart';

extension AppLocalizationsScaleKeys on AppLocalizations {
  // ignore: cyclomatic_complexity
  String resolveKey(String key) => switch (key) {
    // ── Severity (used by GCS and as fallback) ────────────────────────
    'severityNone' => severityNone,
    'severityMild' => severityMild,
    'severityModerate' => severityModerate,
    'severitySevere' => severitySevere,

    // ── GCS labels ────────────────────────────────────────────────────
    'gcsEyeLabel' => gcsEyeLabel,
    'gcsVerbalLabel' => gcsVerbalLabel,
    'gcsMotorLabel' => gcsMotorLabel,
    // GCS options
    'gcsEyeOpt1' => gcsEyeOpt1,
    'gcsEyeOpt2' => gcsEyeOpt2,
    'gcsEyeOpt3' => gcsEyeOpt3,
    'gcsEyeOpt4' => gcsEyeOpt4,
    'gcsVerbalOpt1' => gcsVerbalOpt1,
    'gcsVerbalOpt2' => gcsVerbalOpt2,
    'gcsVerbalOpt3' => gcsVerbalOpt3,
    'gcsVerbalOpt4' => gcsVerbalOpt4,
    'gcsVerbalOpt5' => gcsVerbalOpt5,
    'gcsMotorOpt1' => gcsMotorOpt1,
    'gcsMotorOpt2' => gcsMotorOpt2,
    'gcsMotorOpt3' => gcsMotorOpt3,
    'gcsMotorOpt4' => gcsMotorOpt4,
    'gcsMotorOpt5' => gcsMotorOpt5,
    'gcsMotorOpt6' => gcsMotorOpt6,

    // ── ABCD2 interpretations ─────────────────────────────────────────
    'abcd2RiskLow' => abcd2RiskLow,
    'abcd2RiskModerate' => abcd2RiskModerate,
    'abcd2RiskHigh' => abcd2RiskHigh,

    // ── Barthel interpretations ───────────────────────────────────────
    'barthelInterpIndependent' => barthelInterpIndependent,
    'barthelInterpMild' => barthelInterpMild,
    'barthelInterpModerate' => barthelInterpModerate,
    'barthelInterpSevere' => barthelInterpSevere,
    'barthelInterpTotal' => barthelInterpTotal,

    // ── Rankin interpretations ────────────────────────────────────────
    'rankinInterp0' => rankinInterp0,
    'rankinInterp1' => rankinInterp1,
    'rankinInterp2' => rankinInterp2,
    'rankinInterp3' => rankinInterp3,
    'rankinInterp4' => rankinInterp4,
    'rankinInterp5' => rankinInterp5,
    'rankinInterp6' => rankinInterp6,

    // ── NIHSS interpretations ─────────────────────────────────────────
    'nihssInterp0' => nihssInterp0,
    'nihssInterpMinor' => nihssInterpMinor,
    'nihssInterpModerate' => nihssInterpModerate,
    'nihssInterpModerateSevere' => nihssInterpModerateSevere,
    'nihssInterpSevere' => nihssInterpSevere,

    // ── ABCD2 labels ──────────────────────────────────────────────────
    'abcd2AgeLabel' => abcd2AgeLabel,
    'abcd2BpLabel' => abcd2BpLabel,
    'abcd2ClinicalLabel' => abcd2ClinicalLabel,
    'abcd2DurationLabel' => abcd2DurationLabel,
    'abcd2DiabetesLabel' => abcd2DiabetesLabel,
    // ABCD2 options
    'abcd2AgeOpt0' => abcd2AgeOpt0,
    'abcd2AgeOpt1' => abcd2AgeOpt1,
    'abcd2BpOpt0' => abcd2BpOpt0,
    'abcd2BpOpt1' => abcd2BpOpt1,
    'abcd2ClinicalOpt0' => abcd2ClinicalOpt0,
    'abcd2ClinicalOpt1' => abcd2ClinicalOpt1,
    'abcd2ClinicalOpt2' => abcd2ClinicalOpt2,
    'abcd2DurationOpt0' => abcd2DurationOpt0,
    'abcd2DurationOpt1' => abcd2DurationOpt1,
    'abcd2DurationOpt2' => abcd2DurationOpt2,
    'abcd2DiabetesOpt0' => abcd2DiabetesOpt0,
    'abcd2DiabetesOpt1' => abcd2DiabetesOpt1,

    // ── Barthel labels ────────────────────────────────────────────────
    'barthelItemFeeding' => barthelItemFeeding,
    'barthelItemBathing' => barthelItemBathing,
    'barthelItemGrooming' => barthelItemGrooming,
    'barthelItemDressing' => barthelItemDressing,
    'barthelItemBowels' => barthelItemBowels,
    'barthelItemBladder' => barthelItemBladder,
    'barthelItemToiletUse' => barthelItemToiletUse,
    'barthelItemTransfer' => barthelItemTransfer,
    'barthelItemMobility' => barthelItemMobility,
    'barthelItemStairs' => barthelItemStairs,
    // Barthel options
    'barthelFeedingOpt0' => barthelFeedingOpt0,
    'barthelFeedingOpt5' => barthelFeedingOpt5,
    'barthelFeedingOpt10' => barthelFeedingOpt10,
    'barthelBathingOpt0' => barthelBathingOpt0,
    'barthelBathingOpt5' => barthelBathingOpt5,
    'barthelGroomingOpt0' => barthelGroomingOpt0,
    'barthelGroomingOpt5' => barthelGroomingOpt5,
    'barthelDressingOpt0' => barthelDressingOpt0,
    'barthelDressingOpt5' => barthelDressingOpt5,
    'barthelDressingOpt10' => barthelDressingOpt10,
    'barthelBowelsOpt0' => barthelBowelsOpt0,
    'barthelBowelsOpt5' => barthelBowelsOpt5,
    'barthelBowelsOpt10' => barthelBowelsOpt10,
    'barthelBladderOpt0' => barthelBladderOpt0,
    'barthelBladderOpt5' => barthelBladderOpt5,
    'barthelBladderOpt10' => barthelBladderOpt10,
    'barthelToiletUseOpt0' => barthelToiletUseOpt0,
    'barthelToiletUseOpt5' => barthelToiletUseOpt5,
    'barthelToiletUseOpt10' => barthelToiletUseOpt10,
    'barthelTransferOpt0' => barthelTransferOpt0,
    'barthelTransferOpt5' => barthelTransferOpt5,
    'barthelTransferOpt10' => barthelTransferOpt10,
    'barthelTransferOpt15' => barthelTransferOpt15,
    'barthelMobilityOpt0' => barthelMobilityOpt0,
    'barthelMobilityOpt5' => barthelMobilityOpt5,
    'barthelMobilityOpt10' => barthelMobilityOpt10,
    'barthelMobilityOpt15' => barthelMobilityOpt15,
    'barthelStairsOpt0' => barthelStairsOpt0,
    'barthelStairsOpt5' => barthelStairsOpt5,
    'barthelStairsOpt10' => barthelStairsOpt10,

    // ── Rankin label + options ────────────────────────────────────────
    'rankinScoreLabel' => rankinScoreLabel,
    'rankinLevel0' => rankinLevel0,
    'rankinLevel1' => rankinLevel1,
    'rankinLevel2' => rankinLevel2,
    'rankinLevel3' => rankinLevel3,
    'rankinLevel4' => rankinLevel4,
    'rankinLevel5' => rankinLevel5,
    'rankinLevel6' => rankinLevel6,

    // ── NIHSS labels ──────────────────────────────────────────────────
    'nihss1aLocLabel' => nihss1aLocLabel,
    'nihss1bLocQuestionsLabel' => nihss1bLocQuestionsLabel,
    'nihss1cLocCommandsLabel' => nihss1cLocCommandsLabel,
    'nihss2GazeLabel' => nihss2GazeLabel,
    'nihss3VisualLabel' => nihss3VisualLabel,
    'nihss4FacialLabel' => nihss4FacialLabel,
    'nihss5aMotorArmLLabel' => nihss5aMotorArmLLabel,
    'nihss5bMotorArmRLabel' => nihss5bMotorArmRLabel,
    'nihss6aMotorLegLLabel' => nihss6aMotorLegLLabel,
    'nihss6bMotorLegRLabel' => nihss6bMotorLegRLabel,
    'nihss7AtaxiaLabel' => nihss7AtaxiaLabel,
    'nihss8SensoryLabel' => nihss8SensoryLabel,
    'nihss9LanguageLabel' => nihss9LanguageLabel,
    'nihss10DysarthriaLabel' => nihss10DysarthriaLabel,
    'nihss11NeglectLabel' => nihss11NeglectLabel,
    // NIHSS options
    'nihss1aLocOpt0' => nihss1aLocOpt0,
    'nihss1aLocOpt1' => nihss1aLocOpt1,
    'nihss1aLocOpt2' => nihss1aLocOpt2,
    'nihss1aLocOpt3' => nihss1aLocOpt3,
    'nihss1bLocQuestionsOpt0' => nihss1bLocQuestionsOpt0,
    'nihss1bLocQuestionsOpt1' => nihss1bLocQuestionsOpt1,
    'nihss1bLocQuestionsOpt2' => nihss1bLocQuestionsOpt2,
    'nihss1cLocCommandsOpt0' => nihss1cLocCommandsOpt0,
    'nihss1cLocCommandsOpt1' => nihss1cLocCommandsOpt1,
    'nihss1cLocCommandsOpt2' => nihss1cLocCommandsOpt2,
    'nihss2GazeOpt0' => nihss2GazeOpt0,
    'nihss2GazeOpt1' => nihss2GazeOpt1,
    'nihss2GazeOpt2' => nihss2GazeOpt2,
    'nihss3VisualOpt0' => nihss3VisualOpt0,
    'nihss3VisualOpt1' => nihss3VisualOpt1,
    'nihss3VisualOpt2' => nihss3VisualOpt2,
    'nihss3VisualOpt3' => nihss3VisualOpt3,
    'nihss4FacialOpt0' => nihss4FacialOpt0,
    'nihss4FacialOpt1' => nihss4FacialOpt1,
    'nihss4FacialOpt2' => nihss4FacialOpt2,
    'nihss4FacialOpt3' => nihss4FacialOpt3,
    'nihssMotorArmOpt0' => nihssMotorArmOpt0,
    'nihssMotorArmOpt1' => nihssMotorArmOpt1,
    'nihssMotorArmOpt2' => nihssMotorArmOpt2,
    'nihssMotorArmOpt3' => nihssMotorArmOpt3,
    'nihssMotorArmOpt4' => nihssMotorArmOpt4,
    'nihssMotorArmOpt9' => nihssMotorArmOpt9,
    'nihssMotorLegOpt0' => nihssMotorLegOpt0,
    'nihssMotorLegOpt1' => nihssMotorLegOpt1,
    'nihssMotorLegOpt2' => nihssMotorLegOpt2,
    'nihssMotorLegOpt3' => nihssMotorLegOpt3,
    'nihssMotorLegOpt4' => nihssMotorLegOpt4,
    'nihssMotorLegOpt9' => nihssMotorLegOpt9,
    'nihss7AtaxiaOpt0' => nihss7AtaxiaOpt0,
    'nihss7AtaxiaOpt1' => nihss7AtaxiaOpt1,
    'nihss7AtaxiaOpt2' => nihss7AtaxiaOpt2,
    'nihss7AtaxiaOpt9' => nihss7AtaxiaOpt9,
    'nihss8SensoryOpt0' => nihss8SensoryOpt0,
    'nihss8SensoryOpt1' => nihss8SensoryOpt1,
    'nihss8SensoryOpt2' => nihss8SensoryOpt2,
    'nihss9LanguageOpt0' => nihss9LanguageOpt0,
    'nihss9LanguageOpt1' => nihss9LanguageOpt1,
    'nihss9LanguageOpt2' => nihss9LanguageOpt2,
    'nihss9LanguageOpt3' => nihss9LanguageOpt3,
    'nihss10DysarthriaOpt0' => nihss10DysarthriaOpt0,
    'nihss10DysarthriaOpt1' => nihss10DysarthriaOpt1,
    'nihss10DysarthriaOpt2' => nihss10DysarthriaOpt2,
    'nihss10DysarthriaOpt9' => nihss10DysarthriaOpt9,
    'nihss11NeglectOpt0' => nihss11NeglectOpt0,
    'nihss11NeglectOpt1' => nihss11NeglectOpt1,
    'nihss11NeglectOpt2' => nihss11NeglectOpt2,
    _ => key,
  };
}
